import { useState } from 'react'
import { login, register } from '../../services/api'
import './AuthPage.css'

export default function AuthPage({ mode = 'login' }) {
  const isRegister = mode === 'register'; const [form,setForm]=useState({name:'',role:'client',email:'',password:'',password_confirmation:''}); const [error,setError]=useState(''); const [loading,setLoading]=useState(false)
  const submit=async(e)=>{e.preventDefault();setError('');setLoading(true);try{const {data}=isRegister?await register(form):await login({email:form.email,password:form.password});localStorage.setItem('workman_token',data.token);window.location.href='/dashboard'}catch(err){setError(err.response?.data?.message || 'Something went wrong. Please try again.')}finally{setLoading(false)}}
  return <main className="auth-page"><a className="auth-back" href="/">← Back to WorkMan</a><div className="auth-card"><div className="auth-brand"><span className="brand-mark">W</span> workman<span className="brand-dot">.</span></div><div className="eyebrow">{isRegister?'JOIN THE COMMUNITY':'WELCOME BACK'}</div><h1>{isRegister?'Find your people.':'Good to see you.'}</h1><p className="auth-sub">{isRegister?'Create an account and get trusted help closer to home.':'Log in to keep your local jobs moving.'}</p><form onSubmit={submit}>{isRegister&&<><label>Full name<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="Your name"/></label><fieldset className="role-field"><legend>I’m joining as a</legend><div className="role-options"><button type="button" className={form.role==='client'?'role-option selected':'role-option'} onClick={()=>setForm({...form,role:'client'})}><b>Client</b><small>Find trusted help</small></button><button type="button" className={form.role==='provider'?'role-option selected':'role-option'} onClick={()=>setForm({...form,role:'provider'})}><b>Service provider</b><small>Offer your skills</small></button></div></fieldset></>}<label>Email address<input required type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})} placeholder="you@example.com"/></label><label>Password<input required type="password" minLength="8" value={form.password} onChange={e=>setForm({...form,password:e.target.value})} placeholder="At least 8 characters"/></label>{isRegister&&<label>Confirm password<input required type="password" value={form.password_confirmation} onChange={e=>setForm({...form,password_confirmation:e.target.value})} placeholder="Repeat your password"/></label>}{error&&<div className="form-error">{error}</div>}<button className="button button-dark auth-submit" disabled={loading}>{loading?'Please wait…':isRegister?'Create account':'Log in'} <span>↗</span></button></form><p className="auth-switch">{isRegister?'Already have an account?':'New to WorkMan?'} <a href={isRegister?'/login':'/register'}>{isRegister?'Log in':'Create an account'}</a></p></div></main>
}
